# Generated by Django 4.2.7 on 2024-03-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_vendor_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='image',
            new_name='cover_image',
        ),
    ]
