# Generated by Django 4.2.7 on 2024-03-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_product_life_product_mfd_product_stock_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.PositiveIntegerField(blank=True, default='7', null=True),
        ),
    ]
