# Generated by Django 4.2.7 on 2024-04-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_cartorderitems_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
